dataformat: video
jobs_info:
  examplejob1:
    datasetname: videoname1
    format: .avi
    numframes2pick: 25
    start_point_proportion: 0.1
    end_point_proportion: 1
    selection_mode: motion_pca_cluster #base || motion_pca_cluster
    labeled_datasetname: training_dataset1 
  examplejob2:
    datasetname: videoname2
    format: .avi
    numframes2pick: 30
    start_point_proportion: 0
    end_point_proportion: 0.95
    selection_mode: motion_pca_cluster #base || motion_pca_cluster
    labeled_datasetname: training_dataset1 

bodyparts: [Hand, Finger1, Tongue, Joystick1, Joystick2]
skeleton: 
labelers: [[labeler1name, labeler1@columbia.edu], [labeler2name, labeler2@columbia.edu]]
fullinstruct: please complete the labeling job
shortinstruct: please label
prevneurocaasjobID: None